swagger: "2.0"
info: {}
basePath: /api/v1
paths: {}
definitions:
  models.Haouxuan:
    title: Haouxuan
    type: object
    properties:
      id:
        type: integer
        format: int64
  models.UserRelated:
    title: UserRelated
    type: object
    properties:
      id:
        type: integer
        format: int64
